### ISSUE TITLE
Can't generate migrations with alembic against redshift cluster

### ISSUE THREAD

**Issue by fizyk** [sqlalchemy-redshift/sqlalchemy-redshift#127]
Pretty long traceback due to use wrapping alembic within click based command:

```
Traceback (most recent call last):
  File "/home/gsliwinski/.virtualenvs/x/bin/dw", line 11, in <module>
    load_entry_point('dw', 'console_scripts', 'dw')()
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/gsliwinski/dw/src/dw/scripts/decorators.py", line 11, in call_with_app_context
    return cmd(*args, **kwargs)
  File "/home/gsliwinski/dw/src/dw/scripts/alembic_migrations.py", line 137, in autogenerate
    alembic_ctx = command.revision(alembic_config(click_ctx.obj['DB']), autogenerate=True, message=message)
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/alembic/command.py", line 176, in revision
    script_directory.run_env()
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/alembic/util/compat.py", line 75, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "alembic/env.py", line 88, in <module>
    run_migrations_online()
  File "alembic/env.py", line 82, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 321, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/alembic/command.py", line 156, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/alembic/autogenerate/api.py", line 415, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/alembic/autogenerate/api.py", line 451, in _run_environment
    autogen_context, migration_script)
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/alembic/autogenerate/compare.py", line 22, in _populate_migration_script
    _produce_net_changes(autogen_context, upgrade_ops)
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/alembic/autogenerate/compare.py", line 38, in _produce_net_changes
    schemas = set(inspector.get_schema_names())
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 158, in get_schema_names
    info_cache=self.info_cache)
  File "<string>", line 2, in get_schema_names
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 54, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2349, in get_schema_names
    ).columns(nspname=sqltypes.Unicode))
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/gsliwinski/.virtualenvs/x/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
TypeError: 'dict' object does not support indexing
```

**Comment by fizyk** [comment]
I should note that it only happens whenever the redshift dialect is being selected.

**Comment by TeddyCr** [comment]
Thank you for your contribution and interest in sqlalchemy-redshift. With the help of the OpenMetadata engineering team I recently released sqlalchemy-redshift 1.0.0 with support for SQLAlchemy 2.

With this recent change I'll be closing open tickets and PRs. If you find your issue or PR still relevant for sqlalchemy-redshift v1.0.0, please reopen the ticket.

You can find more information here https://medium.com/p/1388d8dec83d
