### ISSUE TITLE
Alembic generate revision: NoSuchTableError 

### ISSUE THREAD

**Issue by gregbrowndev** [sqlalchemy-redshift/sqlalchemy-redshift#208]
The exception below is thrown when generating a migration with Alembic. The "enterprise.operator" table definitely does exist. However, the problem seems to be due to the quoting of the table name in the key, i.e. enterprise."operator". 

These issues look to be related:
* https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues/137
* https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues/127

Thanks

```
$ alembic revision --autogenerate -m "Remove vehicle_journey_locality table"
INFO  [alembic.runtime.migration] Context impl RedshiftImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy_redshift/dialect.py", line 691, in _get_redshift_relation
    return all_relations[key]
KeyError: 'enterprise."operator"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/bin/alembic", line 10, in <module>
    sys.exit(main())
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/alembic/config.py", line 577, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/alembic/config.py", line 571, in main
    self.run_cmd(cfg, options)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/alembic/config.py", line 548, in run_cmd
    fn(
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/alembic/command.py", line 214, in revision
    script_directory.run_env()
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./src/schemas/enterprise/env.py", line 85, in <module>
    run_migrations_online()
  File "./src/schemas/enterprise/env.py", line 79, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/alembic/runtime/migration.py", line 509, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/alembic/command.py", line 190, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/alembic/autogenerate/api.py", line 442, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/alembic/autogenerate/api.py", line 481, in _run_environment
    compare._populate_migration_script(
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/alembic/autogenerate/compare.py", line 25, in _populate_migration_script
    _produce_net_changes(autogen_context, upgrade_ops)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/alembic/autogenerate/compare.py", line 50, in _produce_net_changes
    comparators.dispatch("schema", autogen_context.dialect.name)(
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/alembic/util/langhelpers.py", line 303, in go
    fn(*arg, **kw)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/alembic/autogenerate/compare.py", line 78, in _autogen_for_tables
    _compare_tables(
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/alembic/autogenerate/compare.py", line 164, in _compare_tables
    inspector.reflecttable(t, None)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 685, in reflecttable
    self._reflect_fk(
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 854, in _reflect_fk
    sa_schema.Table(
  File "<string>", line 2, in __new__
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 559, in __new__
    metadata._remove_table(name, schema)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 554, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 643, in _init
    self._autoload(
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 666, in _autoload
    autoload_with.run_callable(
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1660, in run_callable
    return callable_(self, *args, **kwargs)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 466, in reflecttable
    return insp.reflecttable(
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 685, in reflecttable
    self._reflect_fk(
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 854, in _reflect_fk
    sa_schema.Table(
  File "<string>", line 2, in __new__
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 559, in __new__
    metadata._remove_table(name, schema)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 554, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 643, in _init
    self._autoload(
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 666, in _autoload
    autoload_with.run_callable(
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1660, in run_callable
    return callable_(self, *args, **kwargs)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 466, in reflecttable
    return insp.reflecttable(
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 648, in reflecttable
    tbl_opts = self.get_table_options(
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 313, in get_table_options
    return self.dialect.get_table_options(
  File "<string>", line 2, in get_table_options
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 52, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy_redshift/dialect.py", line 605, in get_table_options
    table = self._get_redshift_relation(connection, table_name,
  File "/home/gbrown/.cache/pypoetry/virtualenvs/bods-ext-airflow-r4KRMLis-py3.8/lib/python3.8/site-packages/sqlalchemy_redshift/dialect.py", line 693, in _get_redshift_relation
    raise sa.exc.NoSuchTableError(key)
sqlalchemy.exc.NoSuchTableError: enterprise."operator"
```

**Comment by gregbrowndev** [comment]
I am happy to attempt to fix this issue over the next couple of days, as its a major blocker for my project.

However, I'm not familiar enough with setting up the dev environment for such a project. I would appreciate if someone pointed me in the right direction with that and what changes might need to be made in the source code.

P.S. This open merge request looks like it might already fix the issue: https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/pull/184/files/fb25e0d1ec6b7e7496ea7f00157ca42bfb44aee7

**Comment by gregbrowndev** [comment]
OK, I mostly figured out how to set things up:

```
python -m venv .venv
source .venv/bin/activate
python setup.py develop
pip install tox
tox
```

but will likely take some time to figure out the issue

**Comment by novotl** [comment]
I'm also hitting this issue and I'm pretty sure I've found the cause. The problem is in the `unquoted` function and the fact, that table names are quoted sometimes (as seen in the stack trace `sqlalchemy.exc.NoSuchTableError: enterprise."operator"`)

https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/40bddca772beedb5f0de4e01f98ea50a8cab0b84/sqlalchemy_redshift/dialect.py#L682-L693

https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/40bddca772beedb5f0de4e01f98ea50a8cab0b84/sqlalchemy_redshift/dialect.py#L211-L222

There are couple of issues:
- the key you're looking for is `RelationKey("operator", enterprise, ...)`. The key is not in `all_relations` because of the quoted table name. The function `RelationKey.unquoted` is wrong, as it doesn't unquote `enterprise."operator"` because it doesn't start and end with `"`.
- the second problem is that the `RelationKey.unquoted` returns a string, but the keys in the `all_relations` map are of type `RelationKey`.

**Comment by TeddyCr** [comment]
Thank you for your contribution and interest in sqlalchemy-redshift. With the help of the OpenMetadata engineering team I recently released sqlalchemy-redshift 1.0.0 with support for SQLAlchemy 2.

With this recent change I'll be closing open tickets and PRs. If you find your issue or PR still relevant for sqlalchemy-redshift v1.0.0, please reopen the ticket.

You can find more information here https://medium.com/p/1388d8dec83d
