### ISSUE TITLE
Model instance overwritten after commit.

### ISSUE THREAD

**Issue by mpatek** [sqlalchemy-redshift/sqlalchemy-redshift#93]
Hi, I'm using the latest version of the repo with sa v. 1.0.12. I'm noticing some strange behavior if I define a model with an identity column. Here's an example:

```Python
import os

import sqlalchemy as sa
from sqlalchemy.ext import declarative

Base = declarative.declarative_base()


class IdentityExample(Base):
    __tablename__ = 'identity_example'

    id = sa.Column(sa.Integer, primary_key=True, info={'identity': (0, 1)})
    name = sa.Column(sa.String)


engine = sa.create_engine(os.environ['REDSHIFT_URL'])
Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)
RedshiftSession = sa.orm.sessionmaker()
session = RedshiftSession(bind=engine)

example_1 = IdentityExample(name='Example #1')
session.add(example_1)
print("EXAMPLE 1 BEFORE: ", example_1.id, example_1.name)
session.commit()
print("EXAMPLE 1 AFTER: ", example_1.id, example_1.name)

example_2 = IdentityExample(name='Example #2')
session.add(example_2)
print("EXAMPLE 2 BEFORE: ", example_2.id, example_2.name)
session.commit()
print("EXAMPLE 2 AFTER: ", example_2.id, example_2.name)
```

I'd expect to see output like this:

```
EXAMPLE 1 BEFORE:  None Example #1
EXAMPLE 1 AFTER:  0 Example #1
EXAMPLE 2 BEFORE:  None Example #2
EXAMPLE 2 AFTER:  1 Example #2
```

Instead I see this:

```
EXAMPLE 1 BEFORE:  None Example #1
EXAMPLE 1 AFTER:  0 Example #1
EXAMPLE 2 BEFORE:  None Example #2
EXAMPLE 2 AFTER:  0 Example #1
```

Am I making some mistake, or is this a bug? Thanks!

**Comment by graingert** [comment]
Ah yes master is broken, see the tests on Travis. https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/pull/92#issuecomment-242326228

**Comment by MarSoft** [comment]
Similar problem with latest version from pypi - anyway this example still doesn't work:

    EXAMPLE 1 BEFORE:  None Example #1
    Traceback (most recent call last):
      File "test.py", line 50, in <module>
        print("EXAMPLE 1 AFTER: ", example_1.id, example_1.name)
      File "/tmp/env/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
        return self.impl.get(instance_state(instance), dict_)
      File "/tmp/env/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 579, in get
        value = state._load_expired(state, passive)
      File "/tmp/env/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 592, in _load_expired
        self.manager.deferred_scalar_loader(self, toload)
      File "/tmp/env/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 703, in load_scalar_attributes
        raise orm_exc.ObjectDeletedError(state)
    sqlalchemy.orm.exc.ObjectDeletedError: Instance '<IdentityExample at 0x7f0da95b68d0>' has been deleted, or its row is otherwise not present.

If I set `engine.echo = True`, I get the following:

    2017-06-01 09:08:29,163 INFO sqlalchemy.engine.base.Engine select version()
    2017-06-01 09:08:29,163 INFO sqlalchemy.engine.base.Engine {}
    2017-06-01 09:08:29,618 INFO sqlalchemy.engine.base.Engine select current_schema()
    2017-06-01 09:08:29,618 INFO sqlalchemy.engine.base.Engine {}
    2017-06-01 09:08:30,073 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
    2017-06-01 09:08:30,073 INFO sqlalchemy.engine.base.Engine {}
    2017-06-01 09:08:30,301 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
    2017-06-01 09:08:30,301 INFO sqlalchemy.engine.base.Engine {}
    2017-06-01 09:08:30,982 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
    2017-06-01 09:08:30,983 INFO sqlalchemy.engine.base.Engine {'name': u'identity_example'}
    2017-06-01 09:08:31,445 INFO sqlalchemy.engine.base.Engine
    DROP TABLE identity_example
    2017-06-01 09:08:31,445 INFO sqlalchemy.engine.base.Engine {}
    2017-06-01 09:08:31,920 INFO sqlalchemy.engine.base.Engine COMMIT
    2017-06-01 09:08:32,152 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
    2017-06-01 09:08:32,153 INFO sqlalchemy.engine.base.Engine {'name': u'identity_example'}
    1 before None john
    2017-06-01 09:08:32,850 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
    2017-06-01 09:08:32,856 INFO sqlalchemy.engine.base.Engine INSERT INTO identity_example (name) VALUES (%(name)s)
    2017-06-01 09:08:32,857 INFO sqlalchemy.engine.base.Engine {'name': 'Example #1'}
    2017-06-01 09:08:33,331 INFO sqlalchemy.engine.base.Engine COMMIT
    2017-06-01 09:08:33,695 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
    2017-06-01 09:08:33,696 INFO sqlalchemy.engine.base.Engine SELECT identity_example.id AS identity_example_id, identity_example.name AS identity_example_name
    FROM identity_example
    WHERE identity_example.id = %(param_1)s
    2017-06-01 09:08:33,696 INFO sqlalchemy.engine.base.Engine {'param_1': 0}
    Traceback (most recent call last):
      File "test.py", line 50, in <module>
        print("EXAMPLE 1 AFTER: ", example_1.id, example_1.name)
      File "/tmp/env/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
        return self.impl.get(instance_state(instance), dict_)
      File "/tmp/env/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 579, in get
        value = state._load_expired(state, passive)
      File "/tmp/env/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 592, in _load_expired
        self.manager.deferred_scalar_loader(self, toload)
      File "/tmp/env/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 703, in load_scalar_attributes
        raise orm_exc.ObjectDeletedError(state)
    sqlalchemy.orm.exc.ObjectDeletedError: Instance '<IdentityExample at 0x7f0da95b68d0>' has been deleted, or its row is otherwise not present.
    
For me it looks like `redshift-sqlalchemy` uses `ResultProxy.lastrowid`, but for some reason (I could not figure it out yet) that value for RedShift is always `0`, regardless of which ID was created or was not created.

The only way I know to obtain an ID of newly inserted record is to `SELECT max(id) FROM table` within the same transaction, which is probably not consistent but should hopefully work at least partially.

**Comment by TeddyCr** [comment]
Thank you for your contribution and interest in sqlalchemy-redshift. With the help of the OpenMetadata engineering team I recently released sqlalchemy-redshift 1.0.0 with support for SQLAlchemy 2.

With this recent change I'll be closing open tickets and PRs. If you find your issue or PR still relevant for sqlalchemy-redshift v1.0.0, please reopen the ticket.

You can find more information here https://medium.com/p/1388d8dec83d
